### Get products
GET http://localhost:3000/api/v1/products?categories=653d1a1e092a207a4b3c6e26,653d19c1092a207a4b3c6e21&count=3


### Get a single products
GET http://localhost:3000/api/v1/products/653d2602d16e03c3e5989920

### Post/ Create a product
POST http://localhost:3000/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTNkNzYxMjdlOTQ4NTExZGE1YTRkNDIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTg1Mjc5OTAsImV4cCI6MTY5ODYxNDM5MH0.bv5yUBupsaOeAKBrOWhHDehJU6TLyCHikurREVSQpE4

{
    "name": "featured product 2",
    "description": "req.body.description",
    "category": "653d1a1e092a207a4b3c6e26",
    "image": "String.jpg",
    "countInStock": 4,
    "brand": "req.body.brand",
    "numReviews": 0,
    "price": 30,
    "isFeatured": true
}

### Update a product
PUT http://localhost:3000/api/v1/products/653d2619d310b52e946d4161
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTNkNzYxMjdlOTQ4NTExZGE1YTRkNDIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTg1Mjc5OTAsImV4cCI6MTY5ODYxNDM5MH0.bv5yUBupsaOeAKBrOWhHDehJU6TLyCHikurREVSQpE4

{
    "name": "featured product new category 2",
    "description": "req.body.description",
    "category": "653d1a1e092a207a4b3c6e26",
    "image": "String.jpg",
    "countInStock": 4,
    "brand": "req.body.brand",
    "numReviews": 0,
    "isFeatured": true
}

### Delete products
DELETE http://localhost:3000/api/v1/products/653c1bf6392761e461069fb1

### Get product count
GET http://localhost:3000/api/v1/products/get/count

### Get featured product
GET http://localhost:3000/api/v1/products/get/featured?count



###=================================== category =======================================
### Get category
GET http://localhost:3000/api/v1/categories


### get category by id
GET http://localhost:3000/api/v1/categories/653d19c1092a207a4b3c6e21

### Post/ Create a category
POST http://localhost:3000/api/v1/categories
Content-Type: application/json

{
    "name": "computer deltete test",
    "icon": "computer",
    "color": "#494"
}

### Update a category
PUT http://localhost:3000/api/v1/categories/653d19c1092a207a4b3c6e21
Content-Type: application/json

{
    
    "icon": "computer updated new",
    "color": "#493444"
}


### Delete a category
DELETE  http://localhost:3000/api/v1/categories/653d1b3